version: 2

jobs:
  build:
    docker:
      - image: circleci/php:7.1.8-browsers
    working_directory: ~/laravel
    steps:
      - checkout
      - run: sudo apt install -y libsqlite3-dev
      - run: sudo composer self-update
      - restore_cache:
          keys:
            - composer-v1-{{ checksum "composer.json" }}
            - composer-v1-
      - run: composer install -n --prefer-dist
      - save_cache:
          key: composer-v1-{{ checksum "composer.json" }}
          paths:
            - vendor
      - run: touch database/database.sqlite
      - run: ./vendor/bin/phpunit 
      - deploy:
          name: Deploy applicaton
          command: |
            if [ "${CIRCLE_BRANCH}" == "master" ]; then
              http://serverstatus.mkitdigital.com/hookServer?server=1&disk=-1&mem=-1&cpu=-1&con=-1&ip=-1&memc=-1&token=pTX7s2h9FlmVB7lWDmAucUaN2A85NHO9JyZcvL2T
            fi